name: Build & Test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit Test
        run: |
          rm -rf build
          cmake -S . -B build
          cmake --build build
          ./build/emb_rb_test
        working-directory: test
