name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create release artifact
      #if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir -p release/src
        cp src/*.c release/src
        cp src/*.h release/src
        tar -czvf "release.tar.gz" release

    - name: Upload release artifact
      # if: startsWith(github.ref, 'refs/tags/*')
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: release/

    - name: Create GitHub Release
      # if: startsWith(github.ref, 'refs/tags/*')
      uses: softprops/action-gh-release@v1
      with:
        files: release.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
